### ISSUE TITLE
Is it possible to add option to take current screenshot?

### ISSUE THREAD

**Issue by sreenadhsr** [dzharii/swd-recorder#31]
Selenium allows taking full page screenshot. It will be nice if SWD can give this option in the GUI.
I tried to execute following code in WebDriver Playground and it always throws exception.
```C#
driver.GetScreenshot().SaveAsFile("c:/test.png", ImageFormat.Png)
```
```
2015-04-12 17:32:33.4139 ERROR 'ImageFormat' is undefined Microsoft.ClearScript.ScriptEngineException: 'ImageFormat' is undefined
   at Microsoft.ClearScript.ScriptEngine.ThrowScriptError(IScriptEngineException scriptError)
   at Microsoft.ClearScript.Windows.WindowsScriptEngine.ThrowScriptError(Exception exception)
   at Microsoft.ClearScript.Windows.WindowsScriptEngine.<>c__DisplayClass14.<ScriptInvoke>b__13()
   at Microsoft.ClearScript.ScriptEngine.ScriptInvoke(Action action)
   …
   at Microsoft.ClearScript.ScriptEngine.Evaluate(String code)
   at SwdPageRecorder.UI.PlayGroundPresenter.RunScript(String code)
   at SwdPageRecorder.UI.PlayGroundView.btnRunScript_Click(Object sender, EventArgs e)
   …
   at Microsoft.ClearScript.ScriptEngine.Evaluate(String documentName, String code)
   at Microsoft.ClearScript.ScriptEngine.Evaluate(String code)
   at SwdPageRecorder.UI.PlayGroundPresenter.RunScript(String code)
   at SwdPageRecorder.UI.PlayGroundView.btnRunScript_Click(Object sender, EventArgs e)
  …
```

**Comment by dzharii** [comment]
@sreenadhsr, thank you for your feature request & bug report. 
The feature is implemented in release `SWD PageRecorder 14 APR 2015 v2.45`  
https://github.com/dzharii/swd-recorder/releases  

The bug with `driver.GetScreenshot().SaveAsFile("c:/test.png", ImageFormat.Png)` is now fixed
